#!/usr/bin/env bash
# transfers a file from our client to a server

# Check number of argument passed
if [[ "$#" -lt 4 ]]; then
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
    exit 1
fi

# Extract command line args
file_path="$1"
ip_addr="$2"
username="$3"
key_path="$4"

# set scp options
scp_options="-o StrictHostKeyChecking=no -i $key_path -r"

scp $scp_options "$file_path" "$username@$ip_addr:~/"
