#!/usr/bin/env bash
# install and configure a web server in a remote server

sudo apt install nginx -y
sudo service nginx start
sudo cat > /var/www/html/index.html << _EOF_
Hello World!
_EOF_

sudo service nginx restart
