#!/usr/bin/env bash
# install and configure a web server in a remote server

sudo apt install nginx -y
sudo cat > /var/www/html/index.html << _EOF_
<html>
    <head>
    </head>
    <body>
        <h1>Hello World!</h1>
    </body>
</html>
_EOF_

sudo service nginx restart
