#!/usr/bin/env bash
# install and configure a web server in a remote server

# install nginx
sudo apt install nginx -y

# start nginx service
sudo service nginx start

# give user ubuntu owner privileges
sudo chown -R ubuntu:ubuntu /var/www/

# make sure user ubuntu has full access to the folder
sudo chmod -R 755 /var/www/

# copy string into index html file
echo "Hello World!" > /var/www/html/index.html

#restart nginx server to effect changes
sudo service nginx restart
