#!/usr/bin/env bash
# install and configure a web server in a remote server

# update package repo
apt update

# install nginx
apt install nginx -y

#create new index page
echo "Hello World!" > /var/www/html/index.html

# create a new location context in nginx config for redirection task
original="root \/var\/www\/html;"

replacement="$original\n\n\tlocation \/redirect_me\n\t\{\n\t\treturn 301 https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4;\n\t\}"

sed -i.bak "s/$original/$replacement/" /etc/nginx/sites-enabled/default

#start nginx server to effect changes
service nginx start
