#!/usr/bin/env bash
#install and configure haproxy to load-balance web01 and web02

# install haproxy for ubuntu focal 20.04
apt install haproxy -y

# configure haproxy to start on server boot
sudo cat >> /etc/default/haproxy <<EOF

# configure haproxy to start on server boot
ENABLED=1
EOF

# start haproxy
sudo service haproxy start

#configure haproxy
haproxy_path="/etc/haproxy/haproxy.cfg"
server1="201159-web-01"
server2="201159-web-02"
server1_ip="54.84.79.181"
server2_ip="52.3.241.176"

sudo cat >> "$haproxy_path" <<EOF

frontend myfrontend
	balance roundrobin
	bind :80
	default_backend jeff_school

backend jeff_school
	balance roundrobin
	option httpchk HEAD /
	default-server check
	server $server1 $server1_ip:80
	server $server2 $server2_ip:80
EOF

#reload haproxy
sudo service haproxy reload
