#!/usr/bin/env bash
#install and configure haproxy to load-balance web01 and web02

#update packages repo
apt update
apt install sudo
apt install cat -y
apt install service -y

# install haproxy
apt-get install --no-install-recommends software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.0 -y
apt-get install haproxy>=2.0.\* -y

# configure haproxy to start on server boot
sudo cat >> /etc/default/haproxy <<EOF
# configure haproxy to start on server boot
ENABLED=1
EOF

#configure haproxy
haproxy_path="/etc/haproxy/haproxy.cfg"
server1="201159-web-01"
server2="201159-web-02"
server1_ip="54.84.79.181"
server2_ip="52.3.241.176"

sudo cat >> "$haproxy_path" <<EOF

frontend myfrontend
	bind :80
	default_backend jeff_school

backend jeff_school
	balance roundrobin
	option httpchk HEAD /
	default-server check
	server $server1 $server1_ip:80
	server $server2 $server2_ip:80
EOF

# start haproxy
sudo service haproxy start
