#!/usr/bin/env bash
# configure an Nginx server to listen on port 80
sed "/^[[:space:]]listen*/d" /etc/nginx/sites-enabled/default
sed -i 's/^server {/\tlisten 80 default_server/' /etc/nginx/sites-enabled/default
service nginx restart
