#!/usr/bin/env bash
# configure an Nginx server to listen on port 80
sed -i 's/^[[:space:]]*listen[[:space:]]*[[:digit:]].*/\n\tlisten 80 default_server;/' /etc/nginx/sites-enabled/default
service nginx restart
