#!/usr/bin/env bash
# print the string "Best School" 10 times with "Hi" on 9th iteration

i=10
while ((i > 0)); do
    echo "Best School"
    if [[ $i == 2 ]]; then
       echo "Hi"
    fi
    ((i -= 1))
done
