#!/usr/bin/env bash
# print numbers 1 to 20 with some variations on different iterations

i=1
while ((i < 21)); do
    echo "$i"
    case $i in
	4) echo "bad luck from China"
	    ;;
	9) echo "bad luck from Japan"
	    ;;
	17) echo "bad luck from Italy"
	   ;;
    esac
    ((i += 1))
done
