#!/usr/bin/env bash
# configure ubuntu server with different localhost ip
sudo cp /etc/hosts ~/hosts.dup
sudo sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.dup
echo -e "8.8.8.8\t\tfacebook.com" >> ~/hosts.dup
cat hosts.dup > /etc/hosts
