#!/usr/bin/env bash
# make nginx run as nginx user instead of root and listen on port 8080
apt update
apt install nginx -y
sudo su nginx
sudo sed -i 's/^[[:space:]]*listen 80/\tlisten 8080/' /etc/nginx/sites-enabled/default
sudo service nginx start
